# SITE CONFIGURATION
baseurl: ""
url: "https://oss.lge.com"

# THEME-SPECIFIC CONFIGURATION
title: LG OSPO Homepage                                  # site's title
description: "Welcome. This is LG Open Source Program Office Homepage."      # used by search engines
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_feature_image: /assets/img/background/main_ospo.png

footer_text: >
  Copyright (c) 2020 LG Electronics

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-174556775-1                                      # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 3
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

